# Generated by Django 5.1.4 on 2025-01-06 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tareas", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tarea",
            old_name="titulo",
            new_name="title",
        ),
    ]
