# Generated by Django 5.1.4 on 2025-01-06 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tareas", "0002_rename_titulo_tarea_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tarea",
            old_name="title",
            new_name="titulo",
        ),
    ]
