# Generated by Django 5.1.4 on 2025-01-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tareas", "0003_rename_title_tarea_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarea",
            name="completado",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
